---
# tasks file for homebridge
- name: Ensure that pigpio is installed
  apt:
    name: pigpio
    state: present

- name: Ensure pigpiod override directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/pigpiod.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remove -l from pigpiod by overriding ExecStart
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/pigpiod.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/pigpiod
    owner: root
    group: root
    mode: '0644'
#  notify: Restart pigpiod

- name: Install getState
  copy:
    dest: /opt/pigpio/cgi/getState
    src: "getState"
    owner: root
    group: root
    mode: '0755'

- name: Install access
  copy:
    dest: /opt/pigpio/access
    src: "access"
    owner: root
    group: root
    mode: '0755'

- name: Allow PiGPIO through UFW
  ufw:
      rule: allow
      port: 8888

- name: Reload systemd and start pigpio service
  ansible.builtin.systemd:
    name: pigpiod.service
    state: started
    enabled: yes
    daemon_reload: yes

