---
- name: Install WireGuard packages
  ansible.builtin.package:
    name: "{{ wireguard_packages }}"
    state: present
  become: yes

- name: Ensure /etc/wireguard directory exists
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate private key if not present (remember to copy to server's wg0.conf)
  ansible.builtin.shell: wg genkey | tee /etc/wireguard/private.key
  args:
    creates: /etc/wireguard/private.key
  register: private_key_generation

- name: Read private key
  ansible.builtin.slurp:
    src: /etc/wireguard/private.key
  register: private_key

- name: Generate public key from private key
  ansible.builtin.shell: echo "{{ private_key['content'] | b64decode }}" | wg pubkey
  register: public_key

- name: Configure WireGuard interface
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  notify: Restart WireGuard

- name: Deploy systemd service for DNS re-resolve
  ansible.builtin.template:
    src: wireguard-reresolve-dns.service.j2
    dest: "/etc/systemd/system/wireguard-reresolve-dns.service"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd timer for periodic DNS re-resolve
  ansible.builtin.template:
    src: wireguard-reresolve-dns.timer.j2
    dest: "/etc/systemd/system/wireguard-reresolve-dns.timer"
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd and start WireGuard DNS re-resolve
  ansible.builtin.systemd:
    name: wireguard-reresolve-dns.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Ensure wg-quick@wg0 is enabled and started
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
