---
# tasks file for raspicam

- name: Enable legacy camera support
  command: raspi-config nonint do_legacy 0
  changed_when: false

- name: Deploy systemd service for raspistill
  ansible.builtin.copy:
    src: "raspistill@.service"
    dest: "/etc/systemd/system/raspistill@.service"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd timer for raspistill
  ansible.builtin.copy:
    src: "raspistill.timer"
    dest: "/etc/systemd/system/raspistill.timer"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd socket for raspistill
  ansible.builtin.template:
    src: raspistill.socket.j2
    dest: "/etc/systemd/system/raspistill.socket"
    owner: root
    group: root
    mode: '0644'

- name: Deploy shell script for raspistill
  ansible.builtin.template:
    src: raspistill.sh.j2
    dest: "/etc/systemd/system/raspistill.sh"
    owner: root
    group: root
    mode: '0755'

- name: Ensure that /mnt/local/photo exists
  ansible.builtin.file:
    path: /mnt/local/photo
    state: directory
    owner: brian
    group: brian
    mode: '0755'

- name: Reload systemd and start raspistill timer
  ansible.builtin.systemd:
    name: raspistill.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Deploy systemd service for raspivid
  ansible.builtin.copy:
    src: "raspivid@.service"
    dest: "/etc/systemd/system/raspivid@.service"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd timer for raspivid
  ansible.builtin.copy:
    src: "raspivid.timer"
    dest: "/etc/systemd/system/raspivid.timer"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd socket for raspivid
  ansible.builtin.template:
    src: raspivid.socket.j2
    dest: "/etc/systemd/system/raspivid.socket"
    owner: root
    group: root
    mode: '0644'

- name: Deploy shell script for raspivid
  ansible.builtin.template:
    src: raspivid.sh.j2
    dest: "/etc/systemd/system/raspivid.sh"
    owner: root
    group: root
    mode: '0755'

- name: Ensure that /mnt/local/video exists
  ansible.builtin.file:
    path: /mnt/local/video
    state: directory
    owner: brian
    group: brian
    mode: '0755'

- name: Reload systemd and start raspivid timer
  ansible.builtin.systemd:
    name: raspivid.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Deploy systemd service for timelapse
  ansible.builtin.copy:
    src: "timelapse.service"
    dest: "/etc/systemd/system/timelapse.service"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd timer for timelapse
  ansible.builtin.copy:
    src: "timelapse.timer"
    dest: "/etc/systemd/system/timelapse.timer"
    owner: root
    group: root
    mode: '0644'

- name: Deploy shell script for timelapse
  ansible.builtin.template:
    src: timelapse.sh.j2
    dest: "/etc/systemd/system/timelapse.sh"
    owner: root
    group: root
    mode: '0755'

- name: Ensure that /mnt/local/timelapse exists
  ansible.builtin.file:
    path: /mnt/local/timelapse
    state: directory
    owner: brian
    group: brian
    mode: '0755'

- name: Reload systemd and start timelapse timer
  ansible.builtin.systemd:
    name: timelapse.timer
    state: started
    enabled: yes
    daemon_reload: yes

