all:
  hosts:
    birdbox2:
      ansible_host: birdbox2.local
      ansible_user: brian
      wireguard_address: 192.168.3.12/24
      wireguard_endpoint: "192.168.58.23:53798"
      wg_ip: 192.168.3.12
      image_prefix: BB2
  children:
    birdboxes:
      hosts:
        birdbox2: {}
    wireguard_clients:
      hosts:
        birdbox2: {}
    nfs_clients:
      hosts:
        birdbox2: {}
    rsync_servers:
      hosts:
        birdbox2: {}
    iperf3_servers:
      hosts:
        birdbox2: {}
    piwatchers:
      hosts:
        birdbox2: {}
    lte_ppp_nodes:
      hosts:
#        birdbox2: {}
    battmon_hosts:
      hosts:
        birdbox2: {}

