[birdboxes]
birdbox0 ansible_host=birdbox0.local ansible_user=brian wireguard_address=192.168.3.10
birdbox1 ansible_host=birdbox1.local ansible_user=brian wireguard_address=192.168.3.11
birdbox2 ansible_host=birdbox2.local ansible_user=brian wireguard_address=192.168.3.12
birdbox3 ansible_host=birdbox3.local ansible_user=brian wireguard_address=192.168.3.13

#[birdbox3]
#birdbox3.local

