[birdboxes]
birdbox1 ansible_host=birdbox1.local ansible_user=brian
birdbox2 ansible_host=birdbox2.local ansible_user=brian
birdbox3 ansible_host=birdbox3.local ansible_user=brian

#[birdbox3]
#birdbox3.local

