---
# tasks file for lte-ppp-node

- name: Enable serial port on Raspberry Pi
  ansible.builtin.command: raspi-config nonint do_serial_hw 1
  become: yes

- name: Disable serial login shell on Raspberry Pi
  ansible.builtin.command: raspi-config nonint do_serial_cons 0
  become: yes

- name: Deploy PPP peer for Clipper LTE
  ansible.builtin.template:
    src: clipper.j2
    dest: "/etc/ppp/peers/clipper"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd service for Clipper LTE
  ansible.builtin.template:
    src: clipper.service.j2
    dest: "/etc/systemd/system/clipper.service"
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd and start Clipper service
  ansible.builtin.systemd:
    name: clipper.service
    state: started
    enabled: yes
    daemon_reload: yes

