---
# tasks file for lte-ppp-node

- name: Configure Raspberry Pi UART to use PL011 on GPIO
  become: true
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE MANAGED UART CONFIG"
    block: |
      enable_uart=1
      dtoverlay=disable-bt
  notify: Reboot raspberry pi
  
- name: Disable serial login shell on Raspberry Pi
  ansible.builtin.command: raspi-config nonint do_serial_cons 1
  become: yes
  changed_when: false

- name: Enable serial port on Raspberry Pi
  ansible.builtin.command: raspi-config nonint do_serial_hw 0
  become: yes
  changed_when: false

- name: Copy lte-simcom to /etc/chatscripts
  ansible.builtin.copy:
    src: lte-simcom
    dest: /etc/chatscripts/lte-simcom
    owner: root
    group: root
    mode: '0644'

- name: Deploy PPP peer for Clipper LTE
  ansible.builtin.template:
    src: clipper.j2
    dest: "/etc/ppp/peers/clipper"
    owner: root
    group: root
    mode: '0644'

- name: Deploy systemd service for Clipper LTE
  ansible.builtin.template:
    src: clipper.service.j2
    dest: "/etc/systemd/system/clipper.service"
    owner: root
    group: root
    mode: '0644'

- name: Stop and disable ModemManager service
  become: true
  ansible.builtin.systemd:
    name: ModemManager.service
    state: stopped
    enabled: no
    masked: yes
  ignore_errors: yes

- name: Reload systemd and start Clipper service
  ansible.builtin.systemd:
    name: clipper.service
    state: started
    enabled: yes
    daemon_reload: yes

